### ISSUE TITLE
Arrange The Order Of Labels

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#400] opened 2022-01-25 01:54 UTC
Maybe there could be an arrow to move the labels up and down so they can be in the order you would like to.

**Comment by Nicko2102** [comment] 2022-01-25 02:16
duplicate of #396

**Comment by BrownieGamingX5** [comment] 2022-01-25 02:31
I'm talking about these "labels":
![20220124183114_1](https://user-images.githubusercontent.com/60493629/150899946-751d1aa7-f2e4-4920-bba5-85b8b273d118.jpg)

**Comment by BrownieGamingX5** [comment] 2022-01-25 02:31
The "status" labels.

**Comment by Nicko2102** [comment] 2022-01-25 02:59
ohhh, lmao i had that idea too but forgot to post it

**Comment by succmydecc** [comment] 2022-01-26 05:39
Huh? What label?

**Comment by Nicko2102** [comment] 2022-01-26 05:51
Not really labels per se, but the status stuff (practice runs, best run, custom text, noclip accuracy)

**Comment by Brittank88** [comment] 2022-01-27 04:09
Even cooler is if (for point 1) you let the menu items in the list be draggable, similar to [this behaviour](https://codepen.io/Defatul/pen/LYEjdzG).

_Originally posted by @Brittank88 in https://github.com/absoIute/Mega-Hack-Pro-Future/issues/412#issuecomment-1022825017_

**Comment by Brittank88** [comment] 2022-01-27 04:10
Should definitely implement the same reordering mechanics for this issue also.

**Comment by absoIute** [comment] 2022-01-28 17:19
will give something like that a shot!

**Comment by absoIute** [comment] 2022-01-30 23:47
This should do it for reordering, not as smooth but works!

https://user-images.githubusercontent.com/20018119/151722975-21457dba-e66b-4751-8f2b-cbf12640d9a7.mp4

**Comment by Nicko2102** [comment] 2022-01-30 23:48
nice!

**Comment by Brittank88** [comment] 2022-01-31 09:42
In addition, would be cool to have live sorting based on line length, as was mentioned in https://github.com/absoIute/Mega-Hack-Pro-Future/issues/441#issuecomment-1025547131.

**Comment by absoIute** [comment] 2022-02-03 22:54
implementation ready for next update!

**Closed by absoIute** 2022-02-03 22:54 UTC
Labels: enhancement, approved, upcoming
