### ISSUE TITLE
Scroll Screen Bug Fix

### ISSUE THREAD

**Issue by pressaltf4please** [absoIute/Mega-Hack-Pro-Future#619] opened 2022-02-19 01:40 UTC
please fix the scroll screen bug. if you dont know, let me explain. the scroll screen bug happens on very high fps. it can either make the player go really fast or slow. By high fps i mean 80K+ or above. PoC: https://youtu.be/F1Tr7cPxILU?t=19

**Comment by NewAlexGamer** [comment] 2022-02-19 14:18
even with the video i don't get what the bug is supposed to be doing

**Comment by pressaltf4please** [comment] 2022-02-19 15:59
> even with the video i don't get what the bug is supposed to be doing

the bug is, is that it will either slow down the player beyond 0.5x speed or above 4x speed

**Comment by absoIute** [comment] 2022-02-19 16:06
are you talking about the weird rotation? I don't see anything else wrong here

**Comment by absoIute** [comment] 2022-02-19 18:38
(closing because alt of blocked account)

**Comment by absoIute** [comment] 2022-02-19 18:39
In addition, bugs caused by silly things like 80,000 FPS aren't something I'm interested in addressing

**Closed by absoIute** 2022-02-19 18:38 UTC
Labels: enhancement
