### ISSUE TITLE
Cant find 3 dlls

### ISSUE THREAD

**Issue by aCupOfKoffi** [absoIute/Mega-Hack-Pro-Future#342] opened 2022-01-02 18:45 UTC
System cant find MSVCP140.dll, VCRUNTIME140.dll, MSVCP140_1.dll. 
<img width="308" alt="Снимок экрана 2022-01-02 214312" src="https://user-images.githubusercontent.com/85884178/147886118-ca25b5be-37ce-4bff-baa0-5e285af5d352.png">
<img width="308" alt="Снимок экрана 2022-01-02 214347" src="https://user-images.githubusercontent.com/85884178/147886120-68074606-4681-4555-9f78-e8695cb13dc9.png">
What should i do?

**Comment by NewAlexGamer** [comment] 2022-01-02 21:18
if you haven't runned the game for the first time yet do it
some of the dlls create when the game is launched for the first time

**Comment by patrykchrymecki** [comment] 2022-01-02 22:43
I had this issue too, I fixed it by installing this. Hope this works for you.
https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by zohnannor** [comment] 2022-01-03 14:35
Duplicate of #252

**Closed** 2022-01-03 17:38 UTC
Labels: duplicate

**Comment by Brittank88** [comment] 2022-01-30 00:38
Duplicate of #252

**Comment by Brittank88** [comment] 2022-01-30 00:38
> Duplicate of #252

A shame this doesn't work properly for non-contributors.

**Comment by Nicko2102** [comment] 2022-01-30 01:24
> A shame this doesn't work properly for non-contributors.

true, but you know some people would abuse it if it did
