### ISSUE TITLE
Speedhack Resets Back To 1x No Matter What Your Speedhack Is Set To Every Time I Reenter Geometry Dash | Possible Fix?

### ISSUE THREAD

**Issue by BrownieGamingX5** [absoIute/Mega-Hack-Pro-Future#291] opened 2021-12-17 04:02 UTC
![20211216200107_1](https://user-images.githubusercontent.com/60493629/146487049-ca322653-2809-43df-96b0-e8fcf2329838.jpg)

**Comment by ExplodingBill** [comment] 2021-12-17 19:34
this is probably to stop issues

**Comment by absoIute** [comment] 2021-12-18 04:02
fixed in beta5

**Closed by absoIute** 2021-12-18 04:02 UTC
Labels: bug

**Comment by Brittank88** [comment] 2022-02-01 01:21
Duplicate of #250
