### ISSUE TITLE
Icon Effects do not work on spider or robot's glows

### ISSUE THREAD

**Issue by Aktimoose** [absoIute/Mega-Hack-Pro-Future#289] opened 2021-12-16 17:14 UTC
Having a custom glow colour does not work when in the spider or robot gamemodes. (This is likely because the their glows are stored separately)

![image](https://user-images.githubusercontent.com/44620677/146416962-a267b7ea-3f07-4106-804b-60b766bf1f93.png)
Glow effect is set to OBJ (aqua) in this screenshot yet it appears red (which is my icon's actual glow colour)

**Comment by absoIute** [comment] 2021-12-18 04:01
fixed in beta5

**Closed by absoIute** 2021-12-18 04:01 UTC
Labels: bug

**Comment by Brittank88** [comment] 2022-02-01 01:20
Duplicate of #247
