### ISSUE TITLE
Overlay Accent Colours

### ISSUE THREAD

**Issue by imgbx** [absoIute/Mega-Hack-Pro-Future#89] opened 2021-09-02 15:02 UTC
hey, I would like to set mhv6 windows the color that I want, not just red. if you could add this I would be thankful (also if we could customize the color of each one would be cooler). thanks!

**Comment by Brittank88** [comment] 2021-09-03 02:03
Actually, closing as this is a duplicate of #70.

**Closed by Brittank88** 2021-09-03 02:03 UTC
Labels: duplicate, enhancement

**Comment by Brittank88** [comment] 2022-01-30 00:44
Duplicate of #70
