### ISSUE TITLE
Auto Safe Mode

### ISSUE THREAD

**Issue by fedqq** [absoIute/Mega-Hack-Pro-Future#281] opened 2021-12-12 14:42 UTC
Pretty self explanatory but basically an option that makes it so that when you turn on any hack it turns on safe mode automatically, and deactivates it after you turn off all the hacks you have enabled (It should only work for hacks which aren't considered legit such as noclip or speedhack). Also safe mode should ask you whether you want to keep the progress at the end of a completion in case someone accidentally leaves it on and completes something hard.

**Comment by zohnannor** [comment] 2021-12-14 06:11
Duplicate of #191

**Closed** 2021-12-18 03:54 UTC
Labels: duplicate

**Comment by Brittank88** [comment] 2022-01-30 00:42
Duplicate of #191
