### ISSUE TITLE
Sort The "Status" Label In Alphabetical Order

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#567] opened 2022-02-11 20:08 UTC
the "status" label is the only one, aside from the right half of megahack which all have very few options that can be simply toggled, to not be sorted in any particular order
![image](https://user-images.githubusercontent.com/86263500/153662669-35d6c6fc-6f4f-47ca-8559-287e78912650.png)

**Comment by BrownieGamingX5** [comment] 2022-02-11 21:09
Oh wow, I never realized that lol. Most likely a bug, but I don't know.

**Comment by Nicko2102** [comment] 2022-02-11 21:09
Duplicate of #400

**Comment by absoIute** [comment] 2022-02-13 21:16
Intended as it was the order I originally wanted (and the order its displayed on-screen), will shuffle it around a bit next update but you'll be able to re-order it yourself anyway

**Closed by absoIute** 2022-02-13 21:16 UTC
Labels: bug
