### ISSUE TITLE
Force Player to be on Top Layer

### ISSUE THREAD

**Issue by ImmensityHQ** [absoIute/Mega-Hack-Pro-Future#473] opened 2022-02-05 15:11 UTC
Hack that forces the player to always be rendered on the top layer, similar to the attempt counter, as well as, if the hack is configured to do so, disable player hide triggers.

**Comment by MainConMan** [comment] 2022-02-05 15:46
Disable hide Triggers is already in the cosmetic tab, but the other ideas are cool :D!

**Comment by Brittank88** [comment] 2022-02-08 00:56
Duplicate of #388

**Comment by Brittank88** [comment] 2022-02-08 00:57
(well, partially, #388 doesn't account for player hide triggers but isn't that also in some other issue? I do not remember...)

**Comment by Brittank88** [comment] 2022-02-08 00:57
@absoIute I'm alright to do this, right? Approving this one is basically just approving #388.

**Closed by Brittank88** 2022-02-08 00:57 UTC
Labels: enhancement, approved
