### ISSUE TITLE
Disable On Death Trigger

### ISSUE THREAD

**Issue by MainConMan** [absoIute/Mega-Hack-Pro-Future#409] opened 2022-01-26 17:47 UTC
Sometimes when playing a level, the level creator will make a death effect that covers the entire screen, which can be annoying, especially in practice mode. The mod will just disable the "On Death" triggers to prevent the death effects from happening.

**Comment by Nicko2102** [comment] 2022-01-26 18:13
love this idea, would make storming summit better to play i think

**Comment by Brittank88** [comment] 2022-02-02 01:32
Duplicate of #445

**Closed** 2022-02-02 15:48 UTC
Labels: duplicate
