### ISSUE TITLE
Better sorting for status text

### ISSUE THREAD

**Issue by Underkirby** [absoIute/Mega-Hack-Pro-Future#441] opened 2022-01-31 05:44 UTC
Idk why but I would kinda like the status text to be ordered from widest to thinnest like a Minecraft Hacked client would, it just looks nicer :D

![2022 Jan 31 16-32-37 1](https://user-images.githubusercontent.com/95105680/151744677-7555ccbb-ffda-41a2-a31a-27418175698f.png)

**Comment by Nicko2102** [comment] 2022-01-31 05:47
duplicate of #400

**Comment by Brittank88** [comment] 2022-01-31 09:41
Duplicate of #400

**Comment by Brittank88** [comment] 2022-01-31 09:41
However, I will note within #400 that live sorting by total line length would be cool.

**Closed by Brittank88** 2022-01-31 09:41 UTC

**Comment by Nicko2102** [comment] 2022-01-31 18:59
> However, I will note within #400 that live sorting by total line length would be cool.

good point, because it can change over time

**Comment by Brittank88** [comment] 2022-02-01 00:42
> for example, if your cps thing is almost the same length as something else, then any time you get to 1 cps or off it it would flip the order, which could be very distracting.

Quite true. There's probably ways to minimise this though, like a 'cooldown' on flipping the same two lines.

Either way, it's one option of a few, and could be disabled in favour of a different method.

**Comment by Underkirby** [comment] 2022-02-01 00:45
Yeah, that makes sense. It could be very distracting.

**Comment by absoIute** [comment] 2022-02-01 13:43
It might be better to just stick to the manual reordering then instead, so everything's just where it's expected
