### ISSUE TITLE
Suggestion: Custom Songs

### ISSUE THREAD

**Issue by porgzy** [absoIute/Mega-Hack-Pro-Future#345] opened 2022-01-04 04:27 UTC
## lol this took way to long to write

-There are a lot of **levels** coming out, with a lot of **songs that try to be different**. Thus, People add custom songs.
Its is quite difficult to actually add custom songs, so why not it be less of a **hassle**?-

-My idea for it is to have a button that **changes** the song into the **newgrounds id** and automatically places it into the **appdata/local/geometrydash** folder, also, There should also be a button that **reverts the song back to the original**.-

-I have no idea how this would happen, because i do not know how to code, but it feels like a **great idea to me.**-

"also yes i did take 15-20 minutes just to write this down, dont judge me please"

**Comment by succmydecc** [comment] 2022-01-05 04:38
Duplicate of #85 and #160

**Comment by Brittank88** [comment] 2022-01-08 09:16
Hey, appreciate the issue, but succ is right, this is (mostly) covered by the extension they've linked, and discussions have already been had about it in the past.

**Closed by Brittank88** 2022-01-08 09:16 UTC
