### ISSUE TITLE
[V7] Config doesn't save

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#285] opened 2021-12-15 11:33 UTC
A week ago, I turned on noclip. But now, each time I open the game, noclip is still on. Even if I turn it off and spam "Save" button. I have no idea why it's like that. Please do something about it.

**Comment by zohnannor** [comment] 2021-12-15 12:21
Duplicate of #255

**Comment by Fl1pNatic** [comment] 2021-12-15 12:49
> Duplicate of #255

Welp, in my defence Jump Hack also turns on

**Comment by absoIute** [comment] 2021-12-18 03:57
fixed in beta5/6

**Closed by absoIute** 2021-12-18 03:57 UTC
Labels: bug, duplicate

**Comment by Brittank88** [comment] 2022-01-30 00:42
Duplicate of #255
