### ISSUE TITLE
Macro Making and Showcasing Tools

### ISSUE THREAD

**Issue by 4-Omega** [absoIute/Mega-Hack-Pro-Future#659] opened 2022-03-05 06:17 UTC
- A macro merger that could merge 2 macros together (accounting for 2 player inputs). This is almost essential for hard 2 player levels.

- Individual player noclip could allow for either player 1 or 2 to have noclip, while the other can still die. This would be useful for botting and merging 2 player macros while also making practicing individual player sections in 2 player levels easier.

- An internal render similar to the one in ReplayBot, TASBot, and oBot.

**Comment by zohnannor** [comment] 2022-03-06 10:39
Duplicate of #123 and a bunch of other issues

**Comment by zohnannor** [comment] 2022-03-06 10:41
I mean, NoClip for 1/2 player and replay system were already suggested

**Comment by zohnannor** [comment] 2022-03-06 10:48
#25 and #605

**Comment by 4-Omega** [comment] 2022-03-06 11:01
> #25 and #605

Didn't see those, sorry. Has the macro merger already been suggested?

**Comment by zohnannor** [comment] 2022-03-06 11:11
Yes if I'm not mistaken, it was suggested in one of several other issues about macros/bots. Tbh it is so obvious and understandable for this feature to be implemented it is not even worth mentioning....

**Closed** 2022-03-06 15:50 UTC

**Comment by Brittank88** [comment] 2022-03-10 00:57
> it is not even worth mentioning

Hmm I'd still at least make sure it's in a checklist somewhere so that we can track development progress properly.

Apart from that I understand what you're saying though.

**Comment by Brittank88** [comment] 2022-03-10 00:58
> Didn't see those, sorry.

All good! Just in future try searching through existing issues first. 😄
