### ISSUE TITLE
Rainbow Effect For Mega Hack Menu

### ISSUE THREAD

**Issue by NewAlexGamer** [absoIute/Mega-Hack-Pro-Future#553] opened 2022-02-08 00:54 UTC
i swear i saw an issue related to this but it simply was "make the menu color customizable" but i can't find it. well it's pretty much the same but it has the rainbow effect instead, you can visualize this by comparing the feature to like almost every keyboard you see these days

edit: found it → #271

**Comment by Brittank88** [comment] 2022-02-08 00:59
Duplicate of #271

**Comment by Brittank88** [comment] 2022-02-08 00:59
I'll mention the RGB aspect of this in #271. Try to do that instead of leaving new issues open.

**Closed by Brittank88** 2022-02-08 00:59 UTC
Labels: duplicate, enhancement
