### ISSUE TITLE
Leaving A Level (Via Menu Button) Freezes Game

### ISSUE THREAD

**Issue by ExplodingBill** [absoIute/Mega-Hack-Pro-Future#263] opened 2021-12-03 21:56 UTC
I'm not sure if this is a problem with GD but can you try fixing it:  [Link to Video](https://youtu.be/JjC0MKQLpQI)

**Comment by absoIute** [comment] 2021-12-11 14:13
Duplicate of #181

**Closed by absoIute** 2021-12-11 14:13 UTC
Labels: bug, duplicate
