### ISSUE TITLE
Death Effect Failure

### ISSUE THREAD

**Issue by abashir7866** [absoIute/Mega-Hack-Pro-Future#51] opened 2021-08-04 06:11 UTC
whenever i die, it just shows my icon. No explosion. stupid question, i know but its genuinely bugging me

![image](https://user-images.githubusercontent.com/79613256/128130698-d6fdc7b6-2b0d-40b8-a5be-64f88008f4e0.png)

**Comment by abashir7866** [comment] 2021-08-04 06:11
lmk if you know how to fix it

**Comment by wiblesss** [comment] 2021-08-04 06:55
Do you have No Death Effect on?

**Comment by Brittank88** [comment] 2021-08-05 01:31
As far as I'm aware this sort of thing can be caused by having it disabled in either MHv6 (No Death Effect as @wiblesss said) or zBot (if you happen to have that installed).

So yeah, I basically have the same question as wiblesss.

**Comment by abashir7866** [comment] 2021-08-05 01:52
No death effect is off, and it just happened once, when I first launched gd after installing mega hack. Its stopped now.

**Comment by abashir7866** [comment] 2021-08-05 01:53
I have about installed but haven't launched it in a while

**Comment by Brittank88** [comment] 2021-08-05 05:09
> No death effect is off, and it just happened once, when I first launched gd after installing mega hack. Its stopped now.

Well, if it has stopped happening, I'm going to close this for now. If it happens again, feel free to reopen this issue! I'll also reopen it if anyone else experiences the same thing.

**Closed by Brittank88** 2021-08-05 05:09 UTC
Labels: bug
