### ISSUE TITLE
Custom Colours / Themes

### ISSUE THREAD

**Issue by RealFX-Code** [absoIute/Mega-Hack-Pro-Future#156] opened 2021-10-31 12:17 UTC
A feature I'd like to see in an extension or in the actual mhv6 is custom themes.

Allowing customization for colors and overall looks in mega hack would be cool to see in the future.
Thanks, RealFX

**Comment by Brittank88** [comment] 2021-11-01 02:13
Appreciate this issue, however, I'll need to close it as a duplicate of #70. Have a nice day!

**Closed by Brittank88** 2021-11-01 02:13 UTC
