### ISSUE TITLE
Scientific Notation In Text Inputs & Text Length

### ISSUE THREAD

**Issue by succmydecc** [absoIute/Mega-Hack-Pro-Future#391] opened 2022-01-22 22:16 UTC
For example if i set my attempt count to 9999999999 it will display 9.999999E+06, and I cant interact with it. Allow for decimal precision in text inputs and allow for text length to be infinite?

**Comment by Nicko2102** [comment] 2022-01-23 03:56
i think that might have happened because the attempt count is an int not a float

**Comment by succmydecc** [comment] 2022-01-23 04:21
smh do you even know what your talking about

**Comment by Nicko2102** [comment] 2022-01-23 04:51
there was literally no reason for you to say that

**Comment by Nicko2102** [comment] 2022-01-23 04:55
also...
![image](https://user-images.githubusercontent.com/83476899/150665470-11d28996-9d04-4c2f-9543-dcc15b79ac2f.png)

**Comment by succmydecc** [comment] 2022-01-23 16:58
I wasn't attempting to be rude yk

**Comment by Nicko2102** [comment] 2022-01-23 18:52
what was the point of saying that then

**Comment by zohnannor** [comment] 2022-01-23 19:12
Duplicate of #322

**Comment by Nicko2102** [comment] 2022-01-23 19:14
I knew i saw it somewhere and was looking for it, thanks

**Comment by succmydecc** [comment] 2022-01-23 19:41
@zohnannor no, thats a issue about scentific notation, this is to allow scentific notations

**Comment by Nicko2102** [comment] 2022-01-23 19:59
your original question is unclear, you reference scientific notation and decimal precision which are two very different things

**Comment by succmydecc** [comment] 2022-01-23 21:05
Sorry, I meant decimal.

**Comment by Nicko2102** [comment] 2022-01-23 21:06
np

**Comment by Brittank88** [comment] 2022-01-24 14:29
I'm going to move this into #322 and suggest support for scientific notation numbers be implemented.

**Comment by Brittank88** [comment] 2022-01-24 14:30
Duplicate of #322

**Closed by Brittank88** 2022-01-24 14:30 UTC
