### ISSUE TITLE
[v7] "Icons" module doesn't work fast enough(I guess)

### ISSUE THREAD

**Issue by Fl1pNatic** [absoIute/Mega-Hack-Pro-Future#311] opened 2021-12-24 09:51 UTC
In MHv6 if you turned on the "Icons" module in Bypasses, even if you restarted the game, icons you picked would stay and not reset if you don't have them unlocked. But in v7 it resets, as if you didn't use the module. Please change that

**Comment by absoIute** [comment] 2021-12-30 19:48
Fixed in beta6

**Closed by absoIute** 2021-12-30 19:48 UTC
Labels: bug

**Comment by Brittank88** [comment] 2022-02-01 01:24
Duplicate of #296
