### ISSUE TITLE
'Auto Song Download' option displaying wrong text in Mega Hack v7

### ISSUE THREAD

**Issue by 4jv** [absoIute/Mega-Hack-Pro-Future#221] opened 2021-11-22 16:51 UTC
basically this
![image](https://user-images.githubusercontent.com/89547516/142902103-6a70cd99-74d2-496b-8308-8961ca52a628.png)

**Comment by Nicko2102** [comment] 2021-11-22 17:15
Duplicate of #217

**Closed** 2021-11-22 21:46 UTC
Labels: duplicate

**Comment by Brittank88** [comment] 2022-01-30 00:43
Duplicate of #217
